[otel]
environment = "development"
log_user_prompt = true
exporter = { otlp-http = {
  endpoint = "http://localhost:4318/v1/logs",
  protocol = "binary"
}}
metrics_exporter = { otlp-http = {
  endpoint = "http://localhost:4318/v1/metrics",
  protocol = "binary"
}}
trace_exporter = { otlp-http = {
  endpoint = "http://localhost:4318/v1/traces",
  protocol = "binary"
}}
