import type { ComponentType, SVGProps } from "react";
import {
  Apple,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  Camera,
  Car,
  CircleDollarSign,
  Coffee,
  Cloud,
  Coins,
  Dumbbell,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Headphones,
  HeartPulse,
  Home,
  Hotel,
  Laptop,
  Landmark,
  Lightbulb,
  Mail,
  Music,
  Package,
  PawPrint,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Shirt,
  ShieldCheck,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Sofa,
  TrainFront,
  Tag,
  Utensils,
  Users,
  WalletCards,
  WashingMachine,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

type Icon = ComponentType<SVGProps<SVGSVGElement>>;

export const categoryIcons = [
  ["tag", "Other", Tag],
  ["shopping-basket", "Groceries", ShoppingBasket],
  ["utensils", "Dining", Utensils],
  ["coffee", "Coffee", Coffee],
  ["home", "Home", Home],
  ["car", "Car", Car],
  ["bus", "Transit", Bus],
  ["fuel", "Fuel", Fuel],
  ["heart-pulse", "Health", HeartPulse],
  ["pill", "Pharmacy", Pill],
  ["dumbbell", "Fitness", Dumbbell],
  ["graduation-cap", "Education", GraduationCap],
  ["book-open", "Books", BookOpen],
  ["gift", "Gifts", Gift],
  ["shirt", "Clothing", Shirt],
  ["gamepad-2", "Entertainment", Gamepad2],
  ["plane", "Travel", Plane],
  ["hotel", "Stay", Hotel],
  ["smartphone", "Phone", Smartphone],
  ["wifi", "Internet", Wifi],
  ["lightbulb", "Utilities", Lightbulb],
  ["wrench", "Repairs", Wrench],
  ["shield-check", "Insurance", ShieldCheck],
  ["paw-print", "Pets", PawPrint],
  ["baby", "Children", Baby],
  ["users", "Family", Users],
  ["landmark", "Taxes", Landmark],
  ["receipt", "Bills", Receipt],
  ["wallet-cards", "Wallet", WalletCards],
  ["banknote", "Cash", Banknote],
  ["circle-dollar-sign", "Income", CircleDollarSign],
  ["briefcase-business", "Work", BriefcaseBusiness],
  ["hand-coins", "Savings", HandCoins],
  ["sparkles", "Personal", Sparkles],
  ["apple", "Fruit", Apple],
  ["cake-slice", "Celebrations", CakeSlice],
  ["pizza", "Pizza", Pizza],
  ["package", "Packages", Package],
  ["bike", "Biking", Bike],
  ["train-front", "Train", TrainFront],
  ["camera", "Camera", Camera],
  ["headphones", "Audio", Headphones],
  ["music", "Music", Music],
  ["laptop", "Laptop", Laptop],
  ["mail", "Mail", Mail],
  ["cloud", "Cloud", Cloud],
  ["flower-2", "Garden", Flower2],
  ["sofa", "Furniture", Sofa],
  ["washing-machine", "Laundry", WashingMachine],
  ["zap", "Energy", Zap],
  ["coins", "Coins", Coins],
] as const satisfies readonly (readonly [string, string, Icon])[];

export type CategoryIconName = (typeof categoryIcons)[number][0];

const iconsByName = new Map<string, { label: string; icon: Icon }>(categoryIcons.map(([name, label, icon]) => [name, { label, icon }]));

export function isCategoryIcon(value: FormDataEntryValue | null): value is CategoryIconName {
  return typeof value === "string" && iconsByName.has(value);
}

export function categoryIcon(name: string | null | undefined) {
  return iconsByName.get(name ?? "tag")?.icon ?? Tag;
}
